version: '3'

services:
  postgres:
    restart: always
    image: postgres:11.6
    container_name: moni-postgres
    volumes:
      - ../bd_data:/var/lib/postgresql/data
    ports:
      - 5433:5432
  
  backend:
    restart: always
    container_name: moni-back
    build: ./
    command: >
      bash -c "python wait_for_postgres.py &&
                ./manage.py migrate &&
                ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/code
    ports:
      - "8200:8000"
    
    depends_on:
      - postgres



